### ISSUE TITLE
Possible alternative to avoid changing permissions of volume mapped to /znc-data

### ISSUE THREAD

**Issue by marramgg** [znc/znc-docker#31]
Hello,

I'm using the following docker-compose config[0] and find it interesting that every time I `docker compose up`, the permissions of, in this example, `/PATH/TO/znc-config` are changed to 700 systemd-network:systemd-journal. I understand this is due to the changes made in [this script](https://github.com/znc/znc-docker/blob/master/slim/startup-sequence/20-chown.sh#L1-L2) and this is a byproduct of the "znc" user and group existing only within the container.

It seems like other images do allow PUID/PGID to set the permissions matching user settings. Example: `chown -R "\${PUID}":"\${PGID}" ${install_paths}`  from binhex/arch-privoxyvpn `/build/root/install.sh#L91` (can't seem to be able to add the link).

```
  znc:
    image: znc
    container_name: znc
    ports:
      - "12345:12345"
    volumes:
      - /PATH/TO/znc-config:/znc-data
```
